services:
  server:
    build:
      context: ./kylemanna-docker-openvpn
      dockerfile: Dockerfile
      args:
        buildno: 1
    image: kylemanna-openvpn:1
    privileged: true
    restart: always
    cap_add:
      - NET_ADMIN
    ports:
      - "$PUBLIC_PORT:1194/$PROTO"
    volumes:
      - ./ovpn-data:/etc/openvpn